language: generic
os: linux
dist: xenial

git:
  submodules: false # Initalized manually if necessary.

jobs:
  include:

    - name: "Compile for Ass Jam"
      addons:
        apt:
          packages:
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND
      install:
        - tools/ci/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
        - touch +secret/__secret.dme
        - sed -i 's/BUILD_TIME_DAY 01/BUILD_TIME_DAY 13/' _std/__build.dm # Ass Jam occurs on the 13th of the month.
      script:
        - tools/ci/dm.sh -DTRAVISBUILDING -DTRAVIS_ASSJAM goonstation.dme

    - name: "Compile & Lint with submodule"
      # https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
      if: |
        (type = push AND repo = goonstation/goonstation) OR \
        (type = pull_request AND head_repo = goonstation/goonstation)
      addons:
        apt:
          packages:
            - libstdc++6:i386
            - rustc
            - cargo
      cache:
        directories:
          - $HOME/BYOND
          - $HOME/SpacemanDMM
      before_install:
        - tools/ci/setup_submodule.sh
      install:
        - tools/ci/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
        - tools/ci/install_spaceman_dmm.sh dreamchecker
      script:
        - ~/dreamchecker
        - tools/ci/dm.sh -DTRAVISBUILDING -DTRAVIS_SUB goonstation.dme
